resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/jag-ermeister/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml

- name: test-app-2
  plan:
  - get: flight-school
    passed: [test-app]
  - task: tests
    file: flight-school/build.yml
